version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: amdin
    volumes:
      - mongo_data:/data/db

  app:
    build: ./app
    container_name: bustimes_model
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/"
    volumes:
      - ./app:/app
    command: ["python3", "fetch_data.py"]

volumes:
  mongo_data:
