name: bus-model Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env File from Secrets
        env:
          PROJECT_ROOT: ${{ vars.PROJECT_ROOT }}
        run: |
          echo "api_key=${{ secrets.API_KEY }}" > .env
          echo "PROJECT_ROOT=${PROJECT_ROOT}" >> .env
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose curl jq

      - name: Build and Start Docker Containers
        run: |
          docker-compose up -d --build

      - name: Run Test Script Inside bus_model Container
        run: |
          docker exec bus_model bash -c "PYTHONPATH=/bus_model pytest -rA tests/ --disable-warnings --cov=."

      - name: Stop and Clean Up Containers
        if: always()
        run: docker-compose down
